package:
  format-version: "1.0.0"
  name: "bootloader_apps_sdcard"
  version: "v3.2.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "v3.7.0"