files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 0FC266630D823D6E97A456B198551090
  logicalPath: config/pic32mz_das_sk/bootloader
  name: bootloader_common.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0FC266630D823D6E97A456B198551090
- generatedChecksum: 52ADEE55295ED43E00E74205B3A6E7E8
  logicalPath: config/pic32mz_das_sk/bootloader
  name: bootloader_sdcard.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 52ADEE55295ED43E00E74205B3A6E7E8
- generatedChecksum: 67010051A2CB3915F27B78F202691B33
  logicalPath: config/pic32mz_das_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67010051A2CB3915F27B78F202691B33
- generatedChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
- generatedChecksum: DB03B7DACF871629F8949E6AA67E1337
  logicalPath: config/pic32mz_das_sk/driver/sdmmc
  name: drv_sdmmc.c
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB03B7DACF871629F8949E6AA67E1337
- generatedChecksum: F0A072D602FF8E337A8405478DA60AB0
  logicalPath: config/pic32mz_das_sk/driver/sdmmc
  name: drv_sdmmc_file_system.c
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F0A072D602FF8E337A8405478DA60AB0
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_das_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 59D642A5B50335F7CD988F013AA4C695
  logicalPath: config/pic32mz_das_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 59D642A5B50335F7CD988F013AA4C695
- generatedChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
  logicalPath: config/pic32mz_das_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config/pic32mz_das_sk/peripheral/cache
  name: plib_cache.c
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config/pic32mz_das_sk/peripheral/cache
  name: plib_cache_local.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config/pic32mz_das_sk/peripheral/cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: F9C8DFBC1C02385D23FA4525A30B65EF
  logicalPath: config/pic32mz_das_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F9C8DFBC1C02385D23FA4525A30B65EF
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config/pic32mz_das_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 13F0751C58CA3EAB32066FCE2901C96C
  logicalPath: config/pic32mz_das_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13F0751C58CA3EAB32066FCE2901C96C
- generatedChecksum: 7D8E18ED1D84C5477436F10C9DE1FF60
  logicalPath: config/pic32mz_das_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7D8E18ED1D84C5477436F10C9DE1FF60
- generatedChecksum: CA41C0116AA86AA82F796A658ADFE1E7
  logicalPath: config/pic32mz_das_sk/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA41C0116AA86AA82F796A658ADFE1E7
- generatedChecksum: A38351FAA4848D332264E92A0D3C4B88
  logicalPath: config/pic32mz_das_sk/peripheral/sdhc
  name: plib_sdhc.c
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A38351FAA4848D332264E92A0D3C4B88
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config/pic32mz_das_sk/system/cache
  name: sys_cache.c
  physicalPath: system/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: 86A89FE2215C9B1F7F9258C7C8772EE5
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 86A89FE2215C9B1F7F9258C7C8772EE5
- generatedChecksum: 349381ED1656BFB8054CE8FF3B506797
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 349381ED1656BFB8054CE8FF3B506797
- generatedChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_das_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: B68110221BEC42FE6B718139BA64DA52
  logicalPath: config/pic32mz_das_sk/system/time
  name: sys_time.c
  physicalPath: system/time/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B68110221BEC42FE6B718139BA64DA52
- generatedChecksum: E63D36D6A8C0E863242DB587C18E5637
  logicalPath: config/pic32mz_das_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E63D36D6A8C0E863242DB587C18E5637
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_das_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 2A39A15E2CF4024A0257BDA249A330BC
  logicalPath: config/pic32mz_das_sk/bootloader
  name: bootloader_common.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 2A39A15E2CF4024A0257BDA249A330BC
- generatedChecksum: 9DB25DB554B63BF0722992CE9C159D1F
  logicalPath: config/pic32mz_das_sk/bootloader
  name: bootloader_sdcard.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DB25DB554B63BF0722992CE9C159D1F
- generatedChecksum: 98459AB5579753DDCA6E4E7BF49BA78F
  logicalPath: config/pic32mz_das_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 98459AB5579753DDCA6E4E7BF49BA78F
- generatedChecksum: 6E088FF2DA32898806108027AF50FB7C
  logicalPath: config/pic32mz_das_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6E088FF2DA32898806108027AF50FB7C
- generatedChecksum: E893307AEE8CAAC8081B75A668A090C9
  logicalPath: config/pic32mz_das_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E893307AEE8CAAC8081B75A668A090C9
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_das_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config/pic32mz_das_sk
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_das_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_das_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: C2DB90A4E4F369FF8F2DADAE23010D25
  logicalPath: config/pic32mz_das_sk/driver/sdmmc
  name: drv_sdmmc.h
  physicalPath: driver/sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: C2DB90A4E4F369FF8F2DADAE23010D25
- generatedChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
  logicalPath: config/pic32mz_das_sk/driver/sdmmc
  name: drv_sdmmc_definitions.h
  physicalPath: driver/sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
- generatedChecksum: 5F51B0F433786A95EFDE6DA2EF03A30F
  logicalPath: config/pic32mz_das_sk/driver/sdmmc
  name: drv_sdmmc_local.h
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 5F51B0F433786A95EFDE6DA2EF03A30F
- generatedChecksum: 187EFA39553617C34D670BFA3AA15C5F
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 187EFA39553617C34D670BFA3AA15C5F
- generatedChecksum: A3FFD9818338493AA10557B4CF9E52A6
  logicalPath: config/pic32mz_das_sk/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: A3FFD9818338493AA10557B4CF9E52A6
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_das_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_das_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_das_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_das_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config/pic32mz_das_sk/peripheral/cache
  name: plib_cache.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config/pic32mz_das_sk/peripheral/cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_das_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config/pic32mz_das_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: 44A9EFA06536DE1713738D859242B11C
  logicalPath: config/pic32mz_das_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 44A9EFA06536DE1713738D859242B11C
- generatedChecksum: FFF8E458FD7BB6E5CED45D1549F80253
  logicalPath: config/pic32mz_das_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFF8E458FD7BB6E5CED45D1549F80253
- generatedChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
  logicalPath: config/pic32mz_das_sk/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
- generatedChecksum: F0C5D6AAAE985637DC98366C5299E48A
  logicalPath: config/pic32mz_das_sk/peripheral/sdhc
  name: plib_sdhc.h
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: F0C5D6AAAE985637DC98366C5299E48A
- generatedChecksum: 5ECD5EF08A9F405606B3339F9D98C332
  logicalPath: config/pic32mz_das_sk/peripheral/sdhc
  name: plib_sdhc_common.h
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5ECD5EF08A9F405606B3339F9D98C332
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config/pic32mz_das_sk/system/cache
  name: sys_cache.h
  physicalPath: system/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mz_das_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: E26A0B284DD5F09B84709E5BE6F3E425
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: E26A0B284DD5F09B84709E5BE6F3E425
- generatedChecksum: 4E8B283AD5759C0A37157EB5ADEB9B81
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 4E8B283AD5759C0A37157EB5ADEB9B81
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mz_das_sk/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_das_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_das_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config/pic32mz_das_sk/system/time
  name: sys_time.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config/pic32mz_das_sk/system/time
  name: sys_time_definitions.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: C7A6D8C5408A42EB1CD2CB277E6EFBF4
  logicalPath: config/pic32mz_das_sk/system/time
  name: sys_time_local.h
  physicalPath: system/time/src
  security: NON_SECURE
  type: HEADER
  userChecksum: C7A6D8C5408A42EB1CD2CB277E6EFBF4
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_das_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_das_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mz_das_sk/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_das_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_das_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_das_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: B9402B5318D299F92A8461B530723E75
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: B9402B5318D299F92A8461B530723E75
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_das_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32
  delimiter: ''
  key: optimization-level
  security: NON_SECURE
  value: -O2
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_das_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
